# Netlify configuration file for firegarden monorepo

# Main site configuration
[build]
  base = "/"
  # This command uses a script to determine which app to build based on SITE_APP environment variable
  command = """
    #!/bin/bash
    pnpm install
    
    if [ "$SITE_APP" = "cms" ]; then
      echo "Building CMS app..."
      APP_DIR="apps/firegarden-cms"
    else
      echo "Building Frontend app..."
      APP_DIR="apps/firegarden-front"
    fi
    
    # Build the selected app
    pnpm turbo build --filter=$APP_DIR
    
    # Prepare deployment directory
    mkdir -p netlify-deploy
    cp -R $APP_DIR/.next/* netlify-deploy/
    cp -R $APP_DIR/public/* netlify-deploy/
  """
  
  # Deploy directory containing only the compiled output and static assets
  publish = "netlify-deploy"

# Environment variables that apply to all contexts
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" # Prevents Netlify npm install
  NEXT_DISABLE_NETLIFY_PLATFORM = "true" # For better Next.js Image compatibility

# Production branch configuration - empty on purpose as we're using environment variables
[context.production]
