# Netlify configuration file for firegarden monorepo

# Default build settings (will not be used directly)
[build]
  base = "/"
  command = "echo 'Please set the SITE_APP environment variable to either cms or front'"
  publish = "/"

# Environment variables that apply to all contexts
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" # Prevents Netlify npm install

# Production context environment variables
[context.production.environment]
  NEXT_DISABLE_NETLIFY_PLATFORM = "true" # Only needed for Next.js frontend

# Specific configuration for CMS site
# Netlify uses this when SITE_APP=cms is set in the site's environment variables
[build.cms]
  base = "apps/firegarden-cms"
  command = "pnpm install && pnpm turbo build --filter=firegarden-cms"
  publish = "dist"

# Specific configuration for Frontend site
# Netlify uses this when SITE_APP=front is set in the site's environment variables
[build.front]
  base = "apps/firegarden-front"
  command = "pnpm install && pnpm turbo build --filter=firegarden-front"
  publish = ".next"
  
  # Updated to support App Router API routes
  functions = ".next/server"
  
  # This tells Netlify how to map Next.js paths to functions
  [[build.front.plugins]]
    package = "@netlify/plugin-nextjs"

# Production configuration
[context.production]
  # This will use the appropriate [build.cms] or [build.front] based on NETLIFY_SITE_NAME

# Branch deploy configuration
[context.branch-deploy]
  # This will use the appropriate [build.cms] or [build.front] based on NETLIFY_SITE_NAME

# Deploy preview configuration
[context.deploy-preview]
  # This will use the appropriate [build.cms] or [build.front] based on NETLIFY_SITE_NAME
