# Netlify configuration file for firegarden monorepo

# Default build settings
[build]
  base = "/"
  # Use a shell script to route to the correct build based on SITE_APP
  command = """
    if [ "$SITE_APP" = "cms" ]; then
      cd apps/firegarden-cms && pnpm install && pnpm turbo build --filter=firegarden-cms
    elif [ "$SITE_APP" = "front" ]; then
      cd apps/firegarden-front && pnpm install && pnpm turbo build --filter=firegarden-front
    else
      echo "Error: SITE_APP must be set to either 'cms' or 'front'" && exit 1
    fi
  """

# Environment variables that apply to all contexts
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" # Prevents Netlify npm install

# Production context environment variables
[context.production.environment]
  NEXT_DISABLE_NETLIFY_PLATFORM = "true" # Only needed for Next.js frontend

# CMS site configuration
[build.cms]
  publish = "apps/firegarden-cms/dist"

# Frontend site configuration
[build.front]
  publish = "apps/firegarden-front/.next"
  [[plugins]]
    package = "@netlify/plugin-nextjs"

# Production configuration
[context.production]
  # This will use the appropriate build based on SITE_APP

# Branch deploy configuration
[context.branch-deploy]
  # This will use the appropriate build based on SITE_APP

# Deploy preview configuration
[context.deploy-preview]
  # This will use the appropriate build based on SITE_APP
