# Netlify configuration file for firegarden monorepo

# Main site configuration
[build]
  base = "/"
  # This command uses a script to determine which app to build based on SITE_APP environment variable
  command = """
    #!/bin/bash
    pnpm install
    
    if [ "$SITE_APP" = "cms" ]; then
      echo "Building CMS app..."
      APP_DIR="apps/firegarden-cms"
      APP_NAME="firegarden-cms"
      BUILD_DIR="dist"
    else
      echo "Building Frontend app..."
      APP_DIR="apps/firegarden-front"
      APP_NAME="firegarden-front"
      BUILD_DIR=".next"
    fi
    
    # Build the selected app using package name, not directory
    pnpm turbo build --filter=$APP_NAME
    
    # Prepare deployment directory
    mkdir -p netlify-deploy
    
    # Check which app is being built and copy appropriate build directory
    if [ "$SITE_APP" = "cms" ]; then
      # For Vite app, copy from dist directory
      if [ -d "$APP_DIR/$BUILD_DIR" ]; then
        cp -R $APP_DIR/$BUILD_DIR/* netlify-deploy/
      else
        echo "Error: Build output directory $APP_DIR/$BUILD_DIR not found"
        exit 1
      fi
    else
      # For Next.js app, copy from .next directory
      if [ -d "$APP_DIR/$BUILD_DIR" ]; then
        cp -R $APP_DIR/$BUILD_DIR/* netlify-deploy/
      else
        echo "Error: Build output directory $APP_DIR/$BUILD_DIR not found"
        exit 1
      fi
    fi
    
    # Verify that public directory exists before copying
    if [ -d "$APP_DIR/public" ]; then
      cp -R $APP_DIR/public/* netlify-deploy/
    else
      echo "Warning: Public directory $APP_DIR/public not found"
    fi
  """
  
  # Deploy directory containing only the compiled output and static assets
  publish = "netlify-deploy"

# Environment variables that apply to all contexts
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" # Prevents Netlify npm install

# Next.js specific configuration for the frontend app
[context.production.environment]
  NEXT_DISABLE_NETLIFY_PLATFORM = "true" # Only needed for Next.js frontend

# Production branch configuration - empty on purpose as we're using environment variables
[context.production]
