# Netlify configuration for the frontend app

[build]
  base = "/"
  package = "apps/firegarden-front"
  command = "cd apps/firegarden-front && pnpm install && pnpm turbo build --filter=firegarden-front"
  publish = "/apps/firegarden-front/.next"
  functions = "/netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" # Prevents Netlify npm install
  NEXT_DISABLE_NETLIFY_PLATFORM = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs" 